/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RefinanceRouteImport } from './routes/refinance'
import { Route as LoanProgramsRouteImport } from './routes/loan-programs'
import { Route as LoanOfficersRouteImport } from './routes/loan-officers'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as GetPrequalifiedRouteImport } from './routes/get-prequalified'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AffordabilityRouteImport } from './routes/affordability'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoanOfficersSlugRouteImport } from './routes/loan-officers.$slug'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const RefinanceRoute = RefinanceRouteImport.update({
  id: '/refinance',
  path: '/refinance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanProgramsRoute = LoanProgramsRouteImport.update({
  id: '/loan-programs',
  path: '/loan-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanOfficersRoute = LoanOfficersRouteImport.update({
  id: '/loan-officers',
  path: '/loan-officers',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const GetPrequalifiedRoute = GetPrequalifiedRouteImport.update({
  id: '/get-prequalified',
  path: '/get-prequalified',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AffordabilityRoute = AffordabilityRouteImport.update({
  id: '/affordability',
  path: '/affordability',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanOfficersSlugRoute = LoanOfficersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LoanOfficersRoute,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affordability': typeof AffordabilityRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/get-prequalified': typeof GetPrequalifiedRoute
  '/learn': typeof LearnRouteWithChildren
  '/loan-officers': typeof LoanOfficersRouteWithChildren
  '/loan-programs': typeof LoanProgramsRoute
  '/refinance': typeof RefinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/loan-officers/$slug': typeof LoanOfficersSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affordability': typeof AffordabilityRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/get-prequalified': typeof GetPrequalifiedRoute
  '/learn': typeof LearnRouteWithChildren
  '/loan-officers': typeof LoanOfficersRouteWithChildren
  '/loan-programs': typeof LoanProgramsRoute
  '/refinance': typeof RefinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/loan-officers/$slug': typeof LoanOfficersSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/affordability': typeof AffordabilityRoute
  '/calculator': typeof CalculatorRoute
  '/contact': typeof ContactRoute
  '/get-prequalified': typeof GetPrequalifiedRoute
  '/learn': typeof LearnRouteWithChildren
  '/loan-officers': typeof LoanOfficersRouteWithChildren
  '/loan-programs': typeof LoanProgramsRoute
  '/refinance': typeof RefinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/loan-officers/$slug': typeof LoanOfficersSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/affordability'
    | '/calculator'
    | '/contact'
    | '/get-prequalified'
    | '/learn'
    | '/loan-officers'
    | '/loan-programs'
    | '/refinance'
    | '/admin/login'
    | '/learn/$slug'
    | '/loan-officers/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/affordability'
    | '/calculator'
    | '/contact'
    | '/get-prequalified'
    | '/learn'
    | '/loan-officers'
    | '/loan-programs'
    | '/refinance'
    | '/admin/login'
    | '/learn/$slug'
    | '/loan-officers/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/affordability'
    | '/calculator'
    | '/contact'
    | '/get-prequalified'
    | '/learn'
    | '/loan-officers'
    | '/loan-programs'
    | '/refinance'
    | '/admin/login'
    | '/learn/$slug'
    | '/loan-officers/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AffordabilityRoute: typeof AffordabilityRoute
  CalculatorRoute: typeof CalculatorRoute
  ContactRoute: typeof ContactRoute
  GetPrequalifiedRoute: typeof GetPrequalifiedRoute
  LearnRoute: typeof LearnRouteWithChildren
  LoanOfficersRoute: typeof LoanOfficersRouteWithChildren
  LoanProgramsRoute: typeof LoanProgramsRoute
  RefinanceRoute: typeof RefinanceRoute
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/refinance': {
      id: '/refinance'
      path: '/refinance'
      fullPath: '/refinance'
      preLoaderRoute: typeof RefinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-programs': {
      id: '/loan-programs'
      path: '/loan-programs'
      fullPath: '/loan-programs'
      preLoaderRoute: typeof LoanProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-officers': {
      id: '/loan-officers'
      path: '/loan-officers'
      fullPath: '/loan-officers'
      preLoaderRoute: typeof LoanOfficersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-prequalified': {
      id: '/get-prequalified'
      path: '/get-prequalified'
      fullPath: '/get-prequalified'
      preLoaderRoute: typeof GetPrequalifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affordability': {
      id: '/affordability'
      path: '/affordability'
      fullPath: '/affordability'
      preLoaderRoute: typeof AffordabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-officers/$slug': {
      id: '/loan-officers/$slug'
      path: '/$slug'
      fullPath: '/loan-officers/$slug'
      preLoaderRoute: typeof LoanOfficersSlugRouteImport
      parentRoute: typeof LoanOfficersRoute
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

interface LoanOfficersRouteChildren {
  LoanOfficersSlugRoute: typeof LoanOfficersSlugRoute
}

const LoanOfficersRouteChildren: LoanOfficersRouteChildren = {
  LoanOfficersSlugRoute: LoanOfficersSlugRoute,
}

const LoanOfficersRouteWithChildren = LoanOfficersRoute._addFileChildren(
  LoanOfficersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AffordabilityRoute: AffordabilityRoute,
  CalculatorRoute: CalculatorRoute,
  ContactRoute: ContactRoute,
  GetPrequalifiedRoute: GetPrequalifiedRoute,
  LearnRoute: LearnRouteWithChildren,
  LoanOfficersRoute: LoanOfficersRouteWithChildren,
  LoanProgramsRoute: LoanProgramsRoute,
  RefinanceRoute: RefinanceRoute,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
