/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TcpaRouteImport } from './routes/tcpa'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as RefinanceRouteImport } from './routes/refinance'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as JoinRouteImport } from './routes/join'
import { Route as GetPrequalifiedRouteImport } from './routes/get-prequalified'
import { Route as FirstTimeBuyerRouteImport } from './routes/first-time-buyer'
import { Route as FindOfficerRouteImport } from './routes/find-officer'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as BuildersRouteImport } from './routes/builders'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AffordabilityRouteImport } from './routes/affordability'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoanProgramsIndexRouteImport } from './routes/loan-programs.index'
import { Route as LoanOfficersIndexRouteImport } from './routes/loan-officers.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LoanProgramsSlugRouteImport } from './routes/loan-programs.$slug'
import { Route as LoanOfficersSlugRouteImport } from './routes/loan-officers.$slug'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as AdminOfficersRouteImport } from './routes/admin.officers'
import { Route as AdminLoginRouteImport } from './routes/admin.login'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TcpaRoute = TcpaRouteImport.update({
  id: '/tcpa',
  path: '/tcpa',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const RefinanceRoute = RefinanceRouteImport.update({
  id: '/refinance',
  path: '/refinance',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const GetPrequalifiedRoute = GetPrequalifiedRouteImport.update({
  id: '/get-prequalified',
  path: '/get-prequalified',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstTimeBuyerRoute = FirstTimeBuyerRouteImport.update({
  id: '/first-time-buyer',
  path: '/first-time-buyer',
  getParentRoute: () => rootRouteImport,
} as any)
const FindOfficerRoute = FindOfficerRouteImport.update({
  id: '/find-officer',
  path: '/find-officer',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildersRoute = BuildersRouteImport.update({
  id: '/builders',
  path: '/builders',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AffordabilityRoute = AffordabilityRouteImport.update({
  id: '/affordability',
  path: '/affordability',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanProgramsIndexRoute = LoanProgramsIndexRouteImport.update({
  id: '/loan-programs/',
  path: '/loan-programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanOfficersIndexRoute = LoanOfficersIndexRouteImport.update({
  id: '/loan-officers/',
  path: '/loan-officers/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanProgramsSlugRoute = LoanProgramsSlugRouteImport.update({
  id: '/loan-programs/$slug',
  path: '/loan-programs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanOfficersSlugRoute = LoanOfficersSlugRouteImport.update({
  id: '/loan-officers/$slug',
  path: '/loan-officers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)
const AdminOfficersRoute = AdminOfficersRouteImport.update({
  id: '/admin/officers',
  path: '/admin/officers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/affordability': typeof AffordabilityRoute
  '/agents': typeof AgentsRoute
  '/builders': typeof BuildersRoute
  '/calculator': typeof CalculatorRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/faq': typeof FaqRoute
  '/find-officer': typeof FindOfficerRoute
  '/first-time-buyer': typeof FirstTimeBuyerRoute
  '/get-prequalified': typeof GetPrequalifiedRoute
  '/join': typeof JoinRoute
  '/learn': typeof LearnRouteWithChildren
  '/licenses': typeof LicensesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/refinance': typeof RefinanceRoute
  '/reviews': typeof ReviewsRoute
  '/tcpa': typeof TcpaRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/officers': typeof AdminOfficersRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/loan-officers/$slug': typeof LoanOfficersSlugRoute
  '/loan-programs/$slug': typeof LoanProgramsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/loan-officers/': typeof LoanOfficersIndexRoute
  '/loan-programs/': typeof LoanProgramsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/affordability': typeof AffordabilityRoute
  '/agents': typeof AgentsRoute
  '/builders': typeof BuildersRoute
  '/calculator': typeof CalculatorRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/faq': typeof FaqRoute
  '/find-officer': typeof FindOfficerRoute
  '/first-time-buyer': typeof FirstTimeBuyerRoute
  '/get-prequalified': typeof GetPrequalifiedRoute
  '/join': typeof JoinRoute
  '/learn': typeof LearnRouteWithChildren
  '/licenses': typeof LicensesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/refinance': typeof RefinanceRoute
  '/reviews': typeof ReviewsRoute
  '/tcpa': typeof TcpaRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/officers': typeof AdminOfficersRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/loan-officers/$slug': typeof LoanOfficersSlugRoute
  '/loan-programs/$slug': typeof LoanProgramsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/loan-officers': typeof LoanOfficersIndexRoute
  '/loan-programs': typeof LoanProgramsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/affordability': typeof AffordabilityRoute
  '/agents': typeof AgentsRoute
  '/builders': typeof BuildersRoute
  '/calculator': typeof CalculatorRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/documents': typeof DocumentsRoute
  '/faq': typeof FaqRoute
  '/find-officer': typeof FindOfficerRoute
  '/first-time-buyer': typeof FirstTimeBuyerRoute
  '/get-prequalified': typeof GetPrequalifiedRoute
  '/join': typeof JoinRoute
  '/learn': typeof LearnRouteWithChildren
  '/licenses': typeof LicensesRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/refinance': typeof RefinanceRoute
  '/reviews': typeof ReviewsRoute
  '/tcpa': typeof TcpaRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/officers': typeof AdminOfficersRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/loan-officers/$slug': typeof LoanOfficersSlugRoute
  '/loan-programs/$slug': typeof LoanProgramsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/loan-officers/': typeof LoanOfficersIndexRoute
  '/loan-programs/': typeof LoanProgramsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/affordability'
    | '/agents'
    | '/builders'
    | '/calculator'
    | '/careers'
    | '/contact'
    | '/documents'
    | '/faq'
    | '/find-officer'
    | '/first-time-buyer'
    | '/get-prequalified'
    | '/join'
    | '/learn'
    | '/licenses'
    | '/press'
    | '/privacy'
    | '/process'
    | '/refinance'
    | '/reviews'
    | '/tcpa'
    | '/terms'
    | '/admin/login'
    | '/admin/officers'
    | '/learn/$slug'
    | '/loan-officers/$slug'
    | '/loan-programs/$slug'
    | '/admin/'
    | '/loan-officers/'
    | '/loan-programs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/affordability'
    | '/agents'
    | '/builders'
    | '/calculator'
    | '/careers'
    | '/contact'
    | '/documents'
    | '/faq'
    | '/find-officer'
    | '/first-time-buyer'
    | '/get-prequalified'
    | '/join'
    | '/learn'
    | '/licenses'
    | '/press'
    | '/privacy'
    | '/process'
    | '/refinance'
    | '/reviews'
    | '/tcpa'
    | '/terms'
    | '/admin/login'
    | '/admin/officers'
    | '/learn/$slug'
    | '/loan-officers/$slug'
    | '/loan-programs/$slug'
    | '/admin'
    | '/loan-officers'
    | '/loan-programs'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/affordability'
    | '/agents'
    | '/builders'
    | '/calculator'
    | '/careers'
    | '/contact'
    | '/documents'
    | '/faq'
    | '/find-officer'
    | '/first-time-buyer'
    | '/get-prequalified'
    | '/join'
    | '/learn'
    | '/licenses'
    | '/press'
    | '/privacy'
    | '/process'
    | '/refinance'
    | '/reviews'
    | '/tcpa'
    | '/terms'
    | '/admin/login'
    | '/admin/officers'
    | '/learn/$slug'
    | '/loan-officers/$slug'
    | '/loan-programs/$slug'
    | '/admin/'
    | '/loan-officers/'
    | '/loan-programs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AffordabilityRoute: typeof AffordabilityRoute
  AgentsRoute: typeof AgentsRoute
  BuildersRoute: typeof BuildersRoute
  CalculatorRoute: typeof CalculatorRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DocumentsRoute: typeof DocumentsRoute
  FaqRoute: typeof FaqRoute
  FindOfficerRoute: typeof FindOfficerRoute
  FirstTimeBuyerRoute: typeof FirstTimeBuyerRoute
  GetPrequalifiedRoute: typeof GetPrequalifiedRoute
  JoinRoute: typeof JoinRoute
  LearnRoute: typeof LearnRouteWithChildren
  LicensesRoute: typeof LicensesRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  RefinanceRoute: typeof RefinanceRoute
  ReviewsRoute: typeof ReviewsRoute
  TcpaRoute: typeof TcpaRoute
  TermsRoute: typeof TermsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOfficersRoute: typeof AdminOfficersRoute
  LoanOfficersSlugRoute: typeof LoanOfficersSlugRoute
  LoanProgramsSlugRoute: typeof LoanProgramsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  LoanOfficersIndexRoute: typeof LoanOfficersIndexRoute
  LoanProgramsIndexRoute: typeof LoanProgramsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tcpa': {
      id: '/tcpa'
      path: '/tcpa'
      fullPath: '/tcpa'
      preLoaderRoute: typeof TcpaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refinance': {
      id: '/refinance'
      path: '/refinance'
      fullPath: '/refinance'
      preLoaderRoute: typeof RefinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-prequalified': {
      id: '/get-prequalified'
      path: '/get-prequalified'
      fullPath: '/get-prequalified'
      preLoaderRoute: typeof GetPrequalifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-time-buyer': {
      id: '/first-time-buyer'
      path: '/first-time-buyer'
      fullPath: '/first-time-buyer'
      preLoaderRoute: typeof FirstTimeBuyerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-officer': {
      id: '/find-officer'
      path: '/find-officer'
      fullPath: '/find-officer'
      preLoaderRoute: typeof FindOfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builders': {
      id: '/builders'
      path: '/builders'
      fullPath: '/builders'
      preLoaderRoute: typeof BuildersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affordability': {
      id: '/affordability'
      path: '/affordability'
      fullPath: '/affordability'
      preLoaderRoute: typeof AffordabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-programs/': {
      id: '/loan-programs/'
      path: '/loan-programs'
      fullPath: '/loan-programs/'
      preLoaderRoute: typeof LoanProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-officers/': {
      id: '/loan-officers/'
      path: '/loan-officers'
      fullPath: '/loan-officers/'
      preLoaderRoute: typeof LoanOfficersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-programs/$slug': {
      id: '/loan-programs/$slug'
      path: '/loan-programs/$slug'
      fullPath: '/loan-programs/$slug'
      preLoaderRoute: typeof LoanProgramsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-officers/$slug': {
      id: '/loan-officers/$slug'
      path: '/loan-officers/$slug'
      fullPath: '/loan-officers/$slug'
      preLoaderRoute: typeof LoanOfficersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/admin/officers': {
      id: '/admin/officers'
      path: '/admin/officers'
      fullPath: '/admin/officers'
      preLoaderRoute: typeof AdminOfficersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AffordabilityRoute: AffordabilityRoute,
  AgentsRoute: AgentsRoute,
  BuildersRoute: BuildersRoute,
  CalculatorRoute: CalculatorRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DocumentsRoute: DocumentsRoute,
  FaqRoute: FaqRoute,
  FindOfficerRoute: FindOfficerRoute,
  FirstTimeBuyerRoute: FirstTimeBuyerRoute,
  GetPrequalifiedRoute: GetPrequalifiedRoute,
  JoinRoute: JoinRoute,
  LearnRoute: LearnRouteWithChildren,
  LicensesRoute: LicensesRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  RefinanceRoute: RefinanceRoute,
  ReviewsRoute: ReviewsRoute,
  TcpaRoute: TcpaRoute,
  TermsRoute: TermsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOfficersRoute: AdminOfficersRoute,
  LoanOfficersSlugRoute: LoanOfficersSlugRoute,
  LoanProgramsSlugRoute: LoanProgramsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  LoanOfficersIndexRoute: LoanOfficersIndexRoute,
  LoanProgramsIndexRoute: LoanProgramsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
